name: salgados_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  sqflite: ^2.3.3+1
  path_provider: ^2.0.0
  image_picker: ^1.2.0
  provider: ^6.1.5+1
  sqflite_common_ffi: ^2.3.6
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  url_launcher: ^6.2.0
  url_launcher_android: ^6.3.18
  url_launcher_windows: ^3.0.0
  webview_flutter: ^4.10.1
  font_awesome_flutter: ^10.9.1
  

  path: any
  http: ^1.5.0
  cloud_functions: ^6.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^6.2.1
  cached_network_image: ^3.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
