name: salgados_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  sqflite: ^2.3.3+1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  provider: ^6.1.2
  sqflite_common_ffi: ^2.3.3+1
  firebase_core: ^2.25.4
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  url_launcher: ^6.1.10 # Explicitly added
  url_launcher_android: ^6.0.0 # Explicitly added for Android
  url_launcher_windows: ^3.0.0 # Explicitly added
  webview_flutter: ^4.0.0 # Added for WhatsApp workaround for Windows
  font_awesome_flutter: ^10.7.0
  

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
