// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6DjV7_4rmNnye3pLdUyTL1TZQYV6GMSM',
    appId: '1:536744890767:android:6c95752cd398784eac7bfa',
    messagingSenderId: '536744890767',
    projectId: 'salgadosapp-e01ce',
    storageBucket: 'salgadosapp-e01ce.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2V7vw-OFfVr0jz2DjfnKYDgrW1-xYd4Q',
    appId: '1:536744890767:ios:28ec7d214e9d0bdaac7bfa',
    messagingSenderId: '536744890767',
    projectId: 'salgadosapp-e01ce',
    storageBucket: 'salgadosapp-e01ce.firebasestorage.app',
    iosBundleId: 'com.example.salgadosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfS2SV5BhS3J-YO-B5QWtpJCwLrn4s6eE',
    appId: '1:536744890767:web:e042051f576f41f4ac7bfa',
    messagingSenderId: '536744890767',
    projectId: 'salgadosapp-e01ce',
    authDomain: 'salgadosapp-e01ce.firebaseapp.com',
    storageBucket: 'salgadosapp-e01ce.firebasestorage.app',
  );
}
